### ISSUE TITLE
Starting ChromeDriver 2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e) on port 9515 Only local connections are allowed. Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code. [1551674454.545][SEVERE]: bind() failed: Address already in use (48) IPv4 port not available. Exiting... logout

### ISSUE THREAD

**Issue by yierika** [rama291041610/Taobao-Autobuy#1]
how to fix this problem ?  Should I install the selenium IDE ????

**Comment by rama291041610** [comment]
> how to fix this problem ? Should I install the selenium IDE ????

I think you don't need to install the selenium IDE. The port may have been used, try to change a port or turn off the firewall.
