### ISSUE TITLE
Taobao没有driver

### ISSUE THREAD

**Issue by monologue1107** [rama291041610/Taobao-Autobuy#2]
(most recent call last):
  File "taobao.py", line 128, in <module>
    t = Taobao()
  File "taobao.py", line 18, in __init__
    self.url = input("https://detail.tmall.com/item.htm?spm=a1z10.1-b-s.w5003-21672572717.25.45e05b740GGVwv&id=593993124865&scene=taobao_shop")
KeyboardInterrupt
Exception ignored in: <function Taobao.__del__ at 0x1092c9378>
Traceback (most recent call last):
  File "taobao.py", line 44, in __del__
    self.driver.quit()
AttributeError: 'Taobao' object has no attribute 'driver'

**Comment by rama291041610** [comment]
Please check the version of your chrome and chromedriver.
